# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.cache/wt [current_project]
set_property parent.project_path C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/Color_mux.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/HSyncComparitor.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/VCounter.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/DisplayAreaComparitor.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/HCounter.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/clk_div.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/VSyncComparitor.v
  C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/sources_1/imports/VGA_Final/Wrapper.v
}
read_xdc C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Clay/Desktop/proj6all/proj6vga/proj6vga.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc]

catch { write_hwdef -file Wrapper.hwdef }
synth_design -top Wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef Wrapper.dcp
catch { report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb }
