# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/project_1/project_1.srcs/sources_1/imports/Basys3_p1/project0_demo_Basys3.v}}
read_xdc {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/project_1/project_1.srcs/constrs_1/imports/Basys3_p1/Project0_Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/project_1/project_1.srcs/constrs_1/imports/Basys3_p1/Project0_Basys3.xdc}}]

synth_design -top led_sw -part xc7a35tcpg236-1
write_checkpoint -noxdef led_sw.dcp
catch { report_utilization -file led_sw_utilization_synth.rpt -pb led_sw_utilization_synth.pb }
