set_property PACKAGE_PIN V17 [get_ports {I[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[0]}]
set_property PACKAGE_PIN V16 [get_ports {I[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[1]}]
set_property PACKAGE_PIN W16 [get_ports {I[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[2]}]
set_property PACKAGE_PIN W17 [get_ports {I[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[3]}]
	
set_property PACKAGE_PIN V15 [get_ports {F}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {F}]
set_property PACKAGE_PIN W14 [get_ports {D}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {D}]
set_property PACKAGE_PIN W13 [get_ports {R}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {R}]
        
set_property PACKAGE_PIN T18 [get_ports {Ein}]						
    set_property IOSTANDARD LVCMOS33 [get_ports {Ein}]
    
set_property PACKAGE_PIN U16 [get_ports {Y[0]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]
set_property PACKAGE_PIN E19 [get_ports {Y[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property PACKAGE_PIN U19 [get_ports {Y[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Y[2]}]
set_property PACKAGE_PIN V19 [get_ports {Y[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {Y[3]}]