# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.cache/wt [current_project]
set_property parent.project_path C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/sources_1/new/sum.v
  C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/sources_1/new/clk_wait.v
  C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/sources_1/new/clkcounter.v
  C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/sources_1/new/top.v
}
read_xdc C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Clay/Desktop/proj6all/projdivider/projdivider.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
