set_property PACKAGE_PIN W7 [get_ports {segment_display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[0]}]
set_property PACKAGE_PIN W6 [get_ports {segment_display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[1]}]
set_property PACKAGE_PIN U8 [get_ports {segment_display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[2]}]
set_property PACKAGE_PIN V8 [get_ports {segment_display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[3]}]
set_property PACKAGE_PIN U5 [get_ports {segment_display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[4]}]
set_property PACKAGE_PIN V5 [get_ports {segment_display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[5]}]
set_property PACKAGE_PIN U7 [get_ports {segment_display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[6]}]
set_property PACKAGE_PIN V7 [get_ports {segment_display[7]}]							
	set_property IOSTANDARD LVCMOS33 [get_ports {segment_display[7]}]

set_property PACKAGE_PIN U18 [get_ports {button[0]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
set_property PACKAGE_PIN T18 [get_ports {button[1]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property PACKAGE_PIN W19 [get_ports {button[2]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property PACKAGE_PIN T17 [get_ports {button[3]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {button[3]}]
#set_property PACKAGE_PIN U17 [get_ports {button[4]}]						
#	set_property IOSTANDARD LVCMOS33 [get_ports {button[4]}]
	
set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]