# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/counter_4_bit.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/Digit_decimal_count.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/decoder_2_4.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/bin2seg_decoder.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/mux_4_to_4.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/controller.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/Clk_Div.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/counter.v}
  {C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/sources_1/imports/Stop_watch/SW.v}
}
read_xdc {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc}}]

read_xdc {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/constrs_1/imports/Nexys4_Master_xdc/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jeffery Fonda/Dropbox/Classes/EE Classes/EE214 Projects/From Dropbox/214/proj7/proj7.srcs/constrs_1/imports/Nexys4_Master_xdc/Basys3_Master.xdc}}]

synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
