# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/project_1.2/project_1.2.cache/wt [current_project]
set_property parent.project_path F:/project_1.2/project_1.2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{F:/project_1.2/project_1.2.srcs/sources_1/new/led sw.v}}
read_xdc F:/project_1.2/project_1.2.srcs/constrs_1/imports/Basys3_p1/Project0_Basys3.xdc
set_property used_in_implementation false [get_files F:/project_1.2/project_1.2.srcs/constrs_1/imports/Basys3_p1/Project0_Basys3.xdc]

synth_design -top led_sw -part xc7a35tcpg236-1
write_checkpoint -noxdef led_sw.dcp
catch { report_utilization -file led_sw_utilization_synth.rpt -pb led_sw_utilization_synth.pb }
