# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Clay/Desktop/multispeed/multispeed.cache/wt [current_project]
set_property parent.project_path C:/Users/Clay/Desktop/multispeed/multispeed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Clay/Desktop/multispeed/multispeed.srcs/sources_1/new/main.v
  C:/Users/Clay/Desktop/multispeed/multispeed.srcs/sources_1/new/mux.v
  C:/Users/Clay/Desktop/multispeed/multispeed.srcs/sources_1/new/sub.v
}
read_xdc C:/Users/Clay/Desktop/multispeed/multispeed.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files C:/Users/Clay/Desktop/multispeed/multispeed.srcs/constrs_1/new/xdc.xdc]

catch { write_hwdef -file clk_divider.hwdef }
synth_design -top clk_divider -part xc7a100tcsg324-1
write_checkpoint -noxdef clk_divider.dcp
catch { report_utilization -file clk_divider_utilization_synth.rpt -pb clk_divider_utilization_synth.pb }
