set_property SRC_FILE_INFO {cfile:D:/onedrive/WSU/EE214/project_1_1/project_1_1.srcs/constrs_1/new/led_constrain.xdc rfile:../../../project_1_1.srcs/constrs_1/new/led_constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {sw}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led}]
