# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/projct_4/project_4.1.4/project_4.1.4.cache/wt [current_project]
set_property parent.project_path D:/projct_4/project_4.1.4/project_4.1.4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/projct_4/project_4.1.4/project_4.1.4.srcs/sources_1/imports/project4.1step4/decoder_3_8.v
read_xdc D:/projct_4/project_4.1.4/project_4.1.4.srcs/constrs_1/new/Basys3.xdc
set_property used_in_implementation false [get_files D:/projct_4/project_4.1.4/project_4.1.4.srcs/constrs_1/new/Basys3.xdc]

synth_design -top decoder_3_8 -part xc7a35tcpg236-1
write_checkpoint -noxdef decoder_3_8.dcp
catch { report_utilization -file decoder_3_8_utilization_synth.rpt -pb decoder_3_8_utilization_synth.pb }
